# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "00_Pipeline.ipynb",
         "TransformeeMaison": "00_Pipeline.ipynb",
         "split_data": "00_Pipeline.ipynb",
         "Pipy": "00_Pipeline.ipynb"}

modules = ["Pipeline.py"]

doc_url = "https://MeherKh.github.io/nbdevPipeline/"

git_url = "https://github.com/MeherKh/nbdevPipeline/tree/master/"

def custom_doc_links(name): return None
